name: Waka Readme

on:
  workflow_dispatch: 
  schedule:
    - cron: "0 3 * * *" # Runs at 6:00 am Kenyan ⌚ everyday


jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: -#
          LANG_COUNT: 7
          SHOW_MASKED_TIME: true
          SHOW_TITLE: true
          
