name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

  Mildly_interesting_facts:
    runs-on: ubuntu-latest
    steps:
      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Africa/Nairobi

  Recent_activity_charts:
    runs-on: ubuntu-latest
    steps:
      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Africa/Nairobi

  Detailed_display:
    runs-on: ubuntu-latest
    steps:
      - name: Detailed display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes


          


